### ISSUE TITLE
when I python run_clm_kv_compression.py, something wrong happened.

### ISSUE THREAD

**Issue by WeiyaoLuo** [DRSY/KV_Compression#1]
`  File "/mylibs/anaconda3/envs/torch2.0.1/lib/python3.8/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 271, in _attn
    attn_scores = attn_scores + attention_mask
RuntimeError: The size of tensor a (256) must match the size of tensor b (65536) at non-singleton dimension 3`
I don't change any original code.

**Comment by DRSY** [comment]
1. comment this line of code: attention_mask = attention_mask.view(batch_size, -1)
2. modify attention_mask = attention_mask[:, None, None, :] to attention_mask = attention_mask[:, None, :, :]
